### PR TITLE
refactor/caleb

### PR DESCRIPTION
**Pull request by calebd-anderson**
- Refactored redundant output into functions
- Fixed null should be left side of operator

### CODE REVIEW

**Comment by lpowell** [comment]
I really like moving the write-host spam to print functions. I need to change the output to add some new data, so I'll implement those changes while I'm at it. Thanks!

**Comment by calebd-anderson** [comment]
> I really like moving the write-host spam to print functions. I need to change the output to add some new data, so I'll implement those changes while I'm at it. Thanks!

Cool, I'll resolve these conflicts.

**Comment by calebd-anderson** [comment]
This PR should now include the additional functionality added by @lpowell from `main`.
Updates in this PR by @calebTree include:
- `ProcessPrint` and `ServicePrint` could be used in a few more instances to improve code reuse
- PowerShell conventions via VSCode autoformat
- minor output aesthetic improvements

**Comment by calebd-anderson** [comment]
closing my ignored PR

**Pull request closed without merging**
